---

- name: "{{ name }} | Configuring secret"
  block:
    - name: "{{ name }} | Creating secret"
      ansible.builtin.include_tasks: "secret_create.yml"
  tags: "{{ name }}"

  rescue:
    - name: "{{ name }} | Deleting service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "{{ name }} | Create secret"
      ansible.builtin.include_tasks: "secret_create.yml"
