---

advertise_addr: 192.168.56.11

api_defaults:
  - name: AMQP_EXCHANGE
    value: xchg_integrations
  - name: AMQP_USER
    value: "{{ rmq.user }}"
  - name: AMQP_PASSWORD
    value: "{{ rmq.password }}"
  - name: AMQP_HOSTNAME
    value: rmq

registry_name: "127.0.0.1:5000"

services:
  - name: api
    version: latest
  - name: app
    version: latest
  - name: converter
    version: latest
  - name: rmq
    version: 3-management
  - name: nginx
    version: latest

non_build_services:
  - name: rmq
    version: 3-management
  - name: nginx
    version: latest

configs:
  converter:
    queue: q_imageProcessor