---

- name: "{{ name }} | Configuring config"
  ansible.builtin.include_tasks: "../config.yml"
  loop:
    - nginx.conf
  loop_control:
    loop_var: config_item

- name: "Deploying {{ name }} services"
  block:
    - name: "{{ name }} | Deploying service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "nginx:{{ version }}"
        state: present
        force_update: true
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 80
            target_port: 80
        configs:
          - config_name: nginx.conf
            filename: "/etc/nginx/nginx.conf"
  tags: "{{ name }}"
