---

- name: "{{ name }} service | Configuring secret"
  ansible.builtin.include_tasks: "../secret.yml"

- name: "{{ name }} service | Service Deployment"
  block:
    - name: "{{ name }} service | Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ registry_name }}/{{ name }}:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3002
            target_port: 3000
        secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
  tags: "{{ name }}"
