---

- name: "{{ name }} service | Configuring secret"
  ansible.builtin.include_tasks: "../secret.yml"

- name: "{{ name }} service | Service Deployment"
  block:
    - name: "{{ name }} service | Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "rabbitmq:3-management"
        state: present
        networks:
          - name: "{{ network_name }}"
        secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
  tags: "{{ name }}"
