---

- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
    # Set up the ansible environment
    - import_tasks: software/repositories.yml
    - import_tasks: software/tweaks.yml
#    - import_tasks: software/packages_utilities.yml
    - import_tasks: software/packages_docker.yml

  rescue:
    - set_fact: task_failed=true
